# Generated by Django 5.2.3 on 2025-06-23 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hivenotes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginview',
            name='account_status',
            field=models.CharField(choices=[('denied', 'denied'), ('accepted', 'accepted'), ('pending', 'pending')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hivenotes_app.manager')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hivenotes_app.reader')),
            ],
        ),
    ]
