# Generated by Django 5.2.3 on 2025-06-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hivenotes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='account_status',
            field=models.CharField(choices=[('pending', 'pending'), ('denied', 'denied'), ('approved', 'approved')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='loginview',
            name='account_status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('pending', 'pending'), ('denied', 'denied')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='members',
            name='account_status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('pending', 'pending'), ('denied', 'denied')], default='pending', max_length=10),
        ),
    ]
