# Generated by Django 5.2.3 on 2025-06-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hivenotes_app', '0002_manager_is_verified_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='manager',
            name='account_status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('denied', 'denied'), ('pending', 'pending')], default='pending', max_length=10),
        ),
    ]
