# Generated by Django 5.2.3 on 2025-06-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hivenotes_app', '0002_loginview_account_status_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginview',
            name='account_status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('denied', 'denied')], default='pending', max_length=10),
        ),
        migrations.DeleteModel(
            name='community',
        ),
    ]
