# Generated by Django 5.2.3 on 2025-06-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hivenotes_app', '0003_remove_manager_is_verified_manager_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='account_status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('pending', 'pending'), ('denied', 'denied')], default='pending', max_length=10),
        ),
    ]
