# Generated by Django 5.2.3 on 2025-06-23 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hivenotes_app', '0003_alter_loginview_account_status_delete_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginview',
            name='account_status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('pending', 'pending'), ('denied', 'denied')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hivenotes_app.manager')),
            ],
        ),
    ]
