# Generated by Django 5.2.3 on 2025-06-24 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hivenotes_app', '0004_alter_loginview_account_status_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginview',
            name='account_status',
            field=models.CharField(choices=[('pending', 'pending'), ('denied', 'denied'), ('accepted', 'accepted')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hivenotes_app.community')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hivenotes_app.reader')),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=2000)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hivenotes_app.members')),
            ],
        ),
    ]
