# Generated by Django 5.2.3 on 2025-06-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hivenotes_app', '0005_alter_loginview_account_status_members_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='account_status',
            field=models.CharField(choices=[('denied', 'denied'), ('pending', 'pending'), ('accepted', 'accepted')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='loginview',
            name='account_status',
            field=models.CharField(choices=[('denied', 'denied'), ('pending', 'pending'), ('accepted', 'accepted')], default='pending', max_length=10),
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
