# Generated by Django 5.2.3 on 2025-06-24 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hivenotes_app', '0006_members_account_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginview',
            name='account_status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('denied', 'denied'), ('pending', 'pending')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='members',
            name='account_status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('denied', 'denied'), ('pending', 'pending')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=2000)),
                ('date', models.DateField(auto_now_add=True)),
                ('account_status', models.CharField(choices=[('approved', 'approved'), ('denied', 'denied'), ('pending', 'pending')], default='pending', max_length=10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hivenotes_app.members')),
            ],
        ),
    ]
