# Generated by Django 5.2.3 on 2025-06-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hivenotes_app', '0007_alter_loginview_account_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='account_status',
            field=models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('denied', 'denied')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='loginview',
            name='account_status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('pending', 'pending'), ('denied', 'denied')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='members',
            name='account_status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('pending', 'pending'), ('denied', 'denied')], default='pending', max_length=10),
        ),
    ]
